WidraSoftCloud.UI/Pages/Pesages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WidraSoftCloud.UI.Data;
using WidraSoftCloud.UI.Models;

namespace WidraSoftCloud.UI.Pages.Pesages
{
    public class CreateModel : PageModel
    {
        private readonly WidraSoftCloud.UI.Data.WidraSoftCloudUIContext _context;

        public CreateModel(WidraSoftCloud.UI.Data.WidraSoftCloudUIContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Pesage Pesage { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Pesage.Add(Pesage);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WidraSoftCloud.UI/Pages/Pesages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WidraSoftCloud.UI.Data;
using WidraSoftCloud.UI.Models;

namespace WidraSoftCloud.UI.Pages.Pesages
{
    public class DeleteModel : PageModel
    {
        private readonly WidraSoftCloud.UI.Data.WidraSoftCloudUIContext _context;

        public DeleteModel(WidraSoftCloud.UI.Data.WidraSoftCloudUIContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Pesage Pesage { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Pesage = await _context.Pesage.FirstOrDefaultAsync(m => m.Id == id);

            if (Pesage == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Pesage = await _context.Pesage.FindAsync(id);

            if (Pesage != null)
            {
                _context.Pesage.Remove(Pesage);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WidraSoftCloud.UI/Pages/Pesages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WidraSoftCloud.UI.Data;
using WidraSoftCloud.UI.Models;

namespace WidraSoftCloud.UI.Pages.Pesages
{
    public class DetailsModel : PageModel
    {
        private readonly WidraSoftCloud.UI.Data.WidraSoftCloudUIContext _context;

        public DetailsModel(WidraSoftCloud.UI.Data.WidraSoftCloudUIContext context)
        {
            _context = context;
        }

        public Pesage Pesage { get; set; }
        public PesageControle Pesagecontrole { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            Pesage = await _context.Pesage.FirstOrDefaultAsync(m => m.UniqueKey == id);
            Pesagecontrole = await _context.PesageControle.FirstOrDefaultAsync(p => p.UniqueKey == id); 

            if (Pesage == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

WidraSoftCloud.UI/Pages/Pesages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WidraSoftCloud.UI.Data;
using WidraSoftCloud.UI.Models;

namespace WidraSoftCloud.UI.Pages.Pesages
{
    public class EditModel : PageModel
    {
        private readonly WidraSoftCloud.UI.Data.WidraSoftCloudUIContext _context;

        public EditModel(WidraSoftCloud.UI.Data.WidraSoftCloudUIContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Pesage Pesage { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Pesage = await _context.Pesage.FirstOrDefaultAsync(m => m.Id == id);

            if (Pesage == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Pesage).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PesageExists(Pesage.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool PesageExists(int id)
        {
            return _context.Pesage.Any(e => e.Id == id);
        }
    }
}

WidraSoftCloud.UI/Pages/Pesages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WidraSoftCloud.UI.Data;
using WidraSoftCloud.UI.Models;

namespace WidraSoftCloud.UI.Pages.Pesages
{
    public class IndexModel : PageModel
    {
        private readonly WidraSoftCloud.UI.Data.WidraSoftCloudUIContext _context;

        public IndexModel(WidraSoftCloud.UI.Data.WidraSoftCloudUIContext context)
        {
            _context = context;
        }

        public IList<Pesage> Pesage { get;set; }
        
        public SelectList Ids { get; set; }
        public SelectList Ponts { get; set; }
        public SelectList Camions { get; set; }
        public SelectList Transporteurs { get; set; }
        public SelectList Produits { get; set; }
        public SelectList Destinations { get; set; }
        public SelectList Clients { get; set; }
        public SelectList Categories { get; set; }
        public SelectList Provenances { get; set; }
        public SelectList Remorques { get; set; }

       
        [BindProperty(SupportsGet = true)]
        public String Id { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Pont { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Camion { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Transporteur { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Produit { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Destination { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Client { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Categorie { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Provenance { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Remorque { get; set; }
        [BindProperty(SupportsGet = true)]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime StartDate { get; set; } = DateTime.Now;
        [BindProperty(SupportsGet = true)]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]        
        public DateTime EndDate { get; set; } = DateTime.Now;
        [BindProperty(SupportsGet = true)]
        public bool IsDateFilterChecked { get; set; }


        private int fn_Surcharge(Int32 weight)
        {
            if (weight < 0)
                return 0;
            else
                return weight;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            IQueryable<string> IdsQuery = from p in _context.Pesage
                                       orderby p.UniqueKey
                                          select p.UniqueKey;
            IQueryable<string> PontsQuery = from p in _context.Pesage
                                            orderby p.SyncId
                                            select p.SyncId;
            IQueryable<string> CamionsQuery = from p in _context.Pesage
                                              orderby p.LibelleCamion
                                              select p.LibelleCamion;
            IQueryable<string> TransporteursQuery = from p in _context.Pesage
                                                    orderby p.LibelleTransporteur
                                                    select p.LibelleTransporteur;
            IQueryable<string> ProduitsQuery = from p in _context.Pesage
                                               orderby p.LibelleProduit
                                               select p.LibelleProduit;
            IQueryable<string> DestinationsQuery = from p in _context.Pesage
                                                   orderby p.LibelleDestination
                                                   select p.LibelleDestination;
            IQueryable<string> ClientsQuery = from p in _context.Pesage
                                              orderby p.LibelleClient
                                              select p.LibelleClient;
            IQueryable<string> CategoriesQuery = from p in _context.Pesage
                                                 orderby p.CategorieCam
                                                 select p.CategorieCam;
            IQueryable<string> ProvenancesQuery = from p in _context.Pesage
                                                  orderby p.LibelleProvenance
                                                  select p.LibelleProvenance;
            IQueryable<string> RemorquesQuery = from p in _context.Pesage
                                                  orderby p.LibelleRemorque
                                                  select p.LibelleRemorque;
            IQueryable<DateTime> DatesQuery = from p in _context.Pesage
                                                  orderby p.DateArrivee
                                                  select p.DateArrivee;


            var pesages = from p in _context.Pesage
                          select p;

            if (Request.Cookies["UsernameCookie"] == null)
            {
                return RedirectToPage("/Password");
            }

            if (!string.IsNullOrEmpty(Id))
            {
                pesages = pesages.Where(p => p.UniqueKey == Id);
            }

            if (!string.IsNullOrEmpty(Pont))
            {
               pesages = pesages.Where(p => p.SyncId == Pont);
            }

            if (!string.IsNullOrEmpty(Camion))
            {
                pesages = pesages.Where(p => p.LibelleCamion == Camion);
            }

            if (!string.IsNullOrEmpty(Transporteur))
            {
                pesages = pesages.Where(p => p.LibelleTransporteur == Transporteur);
            }

            if (!string.IsNullOrEmpty(Produit))
            {
                pesages = pesages.Where(p => p.LibelleProduit == Produit);
            }

            if (!string.IsNullOrEmpty(Destination))
            {
                pesages = pesages.Where(p => p.LibelleDestination == Destination);
            }

            if (!string.IsNullOrEmpty(Client))
            {
                pesages = pesages.Where(p => p.LibelleClient == Client);
            }

            if (!string.IsNullOrEmpty(Categorie))
            {
                pesages = pesages.Where(p => p.CategorieCam == Categorie);
            }

            if (!string.IsNullOrEmpty(Provenance))
            {
                pesages = pesages.Where(p => p.LibelleProvenance == Provenance);
            }

            if (!string.IsNullOrEmpty(Remorque))
            {
                pesages = pesages.Where(p => p.LibelleRemorque == Remorque);
            }

            if (IsDateFilterChecked)
            {
                pesages = pesages.Where(p => p.DateArrivee >= StartDate).Where(p => p.DateArrivee <= EndDate);
            }

            Ids = new SelectList(await IdsQuery.Distinct().ToListAsync());
            Ponts = new SelectList(await PontsQuery.Distinct().ToListAsync());
            Camions = new SelectList(await CamionsQuery.Distinct().ToListAsync());
            Transporteurs = new SelectList(await TransporteursQuery.Distinct().ToListAsync());
            Produits = new SelectList(await ProduitsQuery.Distinct().ToListAsync());
            Destinations = new SelectList(await DestinationsQuery.Distinct().ToListAsync());
            Clients = new SelectList(await ClientsQuery.Distinct().ToListAsync());
            Categories = new SelectList(await CategoriesQuery.Distinct().ToListAsync());
            Provenances = new SelectList(await ProvenancesQuery.Distinct().ToListAsync());
            Remorques = new SelectList(await RemorquesQuery.Distinct().ToListAsync());


            Pesage = await pesages.ToListAsync();
            
            return @Page();
        }

        public FileResult OnPostExport()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[30] { new DataColumn("SyncId"),
                                    new DataColumn("UniqueKey"),
                                    new DataColumn("Id", typeof(Int32)),
                                    new DataColumn("Pont"), 
                                    new DataColumn("Flux"), 
                                    new DataColumn("Tracteur"), 
                                    new DataColumn("Remorque"), 
                                    new DataColumn("Transporteur"), 
                                    new DataColumn("Provenance"), 
                                    new DataColumn("Destination"),
                                    new DataColumn("Produit"),
                                    new DataColumn("Client"),
                                    new DataColumn("Silhouette"),
                                    new DataColumn("Poids Max", typeof(Int32)),
                                    new DataColumn("DatePesee", typeof(DateTime)),
                                    new DataColumn("PTAC", typeof(Int32)),
                                    new DataColumn("Surcharge PTAC", typeof(Int32)),
                                    new DataColumn("Essieu 1"),
                                    new DataColumn("Charge Essieu 1", typeof(Int32)),
                                    new DataColumn("Surcharge Essieu 1", typeof(Int32)),
                                    new DataColumn("Essieu 2"),
                                    new DataColumn("Charge Essieu 2", typeof(Int32)),
                                    new DataColumn("Surcharge Essieu 2", typeof(Int32)),

WidraSoftCloud.UI/Pages/Utilisateurs/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WidraSoftCloud.UI.Data;
using WidraSoftCloud.UI.Models;

namespace WidraSoftCloud.UI.Pages.Utilisateurs
{
    public class CreateModel : PageModel
    {
        private readonly WidraSoftCloud.UI.Data.WidraSoftCloudUIContext _context;

        public CreateModel(WidraSoftCloud.UI.Data.WidraSoftCloudUIContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Utilisateur Utilisateur { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Utilisateur.Add(Utilisateur);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WidraSoftCloud.UI/Pages/Pesages/Create.cshtml
@page
@model WidraSoftCloud.UI.Pages.Pesages.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pesage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pesage.Id" class="control-label"></label>
                <input asp-for="Pesage.Id" class="form-control" />
                <span asp-validation-for="Pesage.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.PontId" class="control-label"></label>
                <input asp-for="Pesage.PontId" class="form-control" />
                <span asp-validation-for="Pesage.PontId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.LibellePont" class="control-label"></label>
                <input asp-for="Pesage.LibellePont" class="form-control" />
                <span asp-validation-for="Pesage.LibellePont" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.CamionId" class="control-label"></label>
                <input asp-for="Pesage.CamionId" class="form-control" />
                <span asp-validation-for="Pesage.CamionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.LibelleCamion" class="control-label"></label>
                <input asp-for="Pesage.LibelleCamion" class="form-control" />
                <span asp-validation-for="Pesage.LibelleCamion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.Flux" class="control-label"></label>
                <input asp-for="Pesage.Flux" class="form-control" />
                <span asp-validation-for="Pesage.Flux" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.TransporteurId" class="control-label"></label>
                <input asp-for="Pesage.TransporteurId" class="form-control" />
                <span asp-validation-for="Pesage.TransporteurId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.LibelleTransporteur" class="control-label"></label>
                <input asp-for="Pesage.LibelleTransporteur" class="form-control" />
                <span asp-validation-for="Pesage.LibelleTransporteur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.ProduitId" class="control-label"></label>
                <input asp-for="Pesage.ProduitId" class="form-control" />
                <span asp-validation-for="Pesage.ProduitId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.LibelleProduit" class="control-label"></label>
                <input asp-for="Pesage.LibelleProduit" class="form-control" />
                <span asp-validation-for="Pesage.LibelleProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.DestiprovenId" class="control-label"></label>
                <input asp-for="Pesage.DestiprovenId" class="form-control" />
                <span asp-validation-for="Pesage.DestiprovenId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.LibelleDestination" class="control-label"></label>
                <input asp-for="Pesage.LibelleDestination" class="form-control" />
                <span asp-validation-for="Pesage.LibelleDestination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.ClientFourniId" class="control-label"></label>
                <input asp-for="Pesage.ClientFourniId" class="form-control" />
                <span asp-validation-for="Pesage.ClientFourniId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.LibelleClient" class="control-label"></label>
                <input asp-for="Pesage.LibelleClient" class="form-control" />
                <span asp-validation-for="Pesage.LibelleClient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.CategorieCam" class="control-label"></label>
                <input asp-for="Pesage.CategorieCam" class="form-control" />
                <span asp-validation-for="Pesage.CategorieCam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.Observations" class="control-label"></label>
                <input asp-for="Pesage.Observations" class="form-control" />
                <span asp-validation-for="Pesage.Observations" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.DateArrivee" class="control-label"></label>
                <input asp-for="Pesage.DateArrivee" class="form-control" />
                <span asp-validation-for="Pesage.DateArrivee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.PoidsNet" class="control-label"></label>
                <input asp-for="Pesage.PoidsNet" class="form-control" />
                <span asp-validation-for="Pesage.PoidsNet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.AgentPesee" class="control-label"></label>
                <input asp-for="Pesage.AgentPesee" class="form-control" />
                <span asp-validation-for="Pesage.AgentPesee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.ProvenanceId" class="control-label"></label>
                <input asp-for="Pesage.ProvenanceId" class="form-control" />
                <span asp-validation-for="Pesage.ProvenanceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.LibelleProvenance" class="control-label"></label>
                <input asp-for="Pesage.LibelleProvenance" class="form-control" />
                <span asp-validation-for="Pesage.LibelleProvenance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pesage.DateSynchronisation" class="control-label"></label>
                <input asp-for="Pesage.DateSynchronisation" class="form-control" />
                <span asp-validation-for="Pesage.DateSynchronisation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WidraSoftCloud.UI/Pages/Pesages/Index.cshtml
@page
@model WidraSoftCloud.UI.Pages.Pesages.IndexModel

@{
    ViewData["Title"] = "Pesages";
}

<h1>Pesages</h1>
<br />
<p>
<form>
    <p>
        Numéro: <select asp-for="Id" asp-items="Model.Ids">
            <option value="">Tout</option>
        </select>
        Pont: <select asp-for="Pont" asp-items="Model.Ponts">
            <option value="">Tout</option>
        </select>
        Tracteur: <select asp-for="Camion" asp-items="Model.Camions">
            <option value="">Tout</option>
        </select>
        Remorque: <select asp-for="Remorque" asp-items="Model.Remorques">
            <option value="">Tout</option>
        </select>
        Transporteur: <select asp-for="Transporteur" asp-items="Model.Transporteurs">
            <option value="">Tout</option>
        </select>
    </p>
    <p>
        Produit: <select asp-for="Produit" asp-items="Model.Produits">
            <option value="">Tout</option>
        </select>

        Destination: <select asp-for="Destination" asp-items="Model.Destinations">
            <option value="">Tout</option>
        </select>

        Client:  <select asp-for="Client" asp-items="Model.Clients">
            <option value="">Tout</option>
        </select>

        Categorie:  <select asp-for="Categorie" asp-items="Model.Categories">
            <option value="">Tout</option>
        </select>
    </p>
    <p>
        Provenance:  <select asp-for="Provenance" asp-items="Model.Provenances">
            <option value="">Tout</option>
        </select>

        Filtre de Date: <input type="checkbox"  asp-for="IsDateFilterChecked" />
                     <input asp-for="StartDate" name="StartDate"/>
                     <input asp-for="EndDate" name="EndDate"/>


        <input style="background-color:#0bb963;color:white;border-radius:3px 4px;" type="submit" value="Rechercher" />
    </p>


</form>
    <form method="post" asp-page-handler="Export" style="margin-bottom:2px">
                     <input type="checkbox"  asp-for="IsDateFilterChecked" hidden="true" />
                     <input asp-for="StartDate" name="StartDate" hidden="true"/>
                     <input asp-for="EndDate" name="EndDate" hidden="true" />
                     <input asp-for="Pont" name="Pont" hidden="true" />
                     <input asp-for="Camion" name="Camion" hidden="true" />
                     <input asp-for="Remorque" name="Remorque" hidden="true" />
                     <input asp-for="Transporteur" name="Transporteur" hidden="true" />
                     <input asp-for="Produit" name="Produit" hidden="true" />
                     <input asp-for="Destination" name="Destination" hidden="true" />
                     <input asp-for="Client" name="Client" hidden="true" />
                     <input asp-for="Categorie" name="Categorie" hidden="true" />
                     <input asp-for="Provenance" name="Provenance" hidden="true" />
        <input style="background-color:#0bb963;color:white;border-radius:3px 4px;" type="submit" value="Exporter Excel"  />
    </form>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].SyncId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].UniqueKey)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].LibellePont)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].LibelleCamion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].LibelleRemorque)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].LibelleProduit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].LibelleClient)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].CategorieCam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].DateArrivee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesage[0].DateSynchronisation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Pesage) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SyncId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UniqueKey)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LibellePont)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LibelleCamion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LibelleRemorque)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LibelleProduit)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.LibelleClient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategorieCam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateArrivee)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DateSynchronisation)
            </td>
            <td style="color:#0bb963;">
                <a style="color:#0bb963" asp-page="./Details" asp-route-id="@item.UniqueKey">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>